<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="KIRMAD" failures="1" tests="2" name="Test1" time="0.084" errors="0" timestamp="28 Aug 2018 11:56:28 GMT">
  <testcase classname="Part4_TestNG.class2" name="demo1" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Part4_TestNG.class2.demo1(class2.java:13)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="Part4_TestNG.class2" name="demo2" time="0.005"/>
  <testcase classname="Part4_TestNG.class2" name="demo3" time="0.0">
    <ignored/>
  </testcase> <!-- demo3 -->
  <testcase classname="Part3.table" name="AlongMain" time="0.0">
    <ignored/>
  </testcase> <!-- AlongMain -->
</testsuite> <!-- Test1 -->
